discord:
  token: T0K3N
  guild: 000000000000000000
google:
  client-id: abc
  client-secret: abc
  email-suffix: @example.com
messages:
  not-whitelisted: You are not whitelisted on this server!
  whitelist-check-error: There was an error while checking the whitelist.
